//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.17929.
// 
#pragma warning disable 1591

namespace AzuPassProfileMgr.TEICOCF.WebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AzuPassSoap", Namespace="http://webservices.cf.minaz.cu/")]
    public partial class AzuPass : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback _LogOnOperationCompleted;
        
        private System.Threading.SendOrPostCallback _LogOnPlusOperationCompleted;
        
        private System.Threading.SendOrPostCallback _getProfileFavoritesOperationCompleted;
        
        private System.Threading.SendOrPostCallback _getServicedApplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _getServiceAdminsOperationCompleted;
        
        private System.Threading.SendOrPostCallback _getProfileManagerURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback _getAboutOperationCompleted;
        
        private System.Threading.SendOrPostCallback _getLogoImageSrcOperationCompleted;
        
        private System.Threading.SendOrPostCallback _getServiceShortNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback _getServiceFullNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback _getListCatOcupacionalesOperationCompleted;
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrepareNewProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPasswdRequerimentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChangeProfilePasswdWarningOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeProfilePasswdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChangeProfileEmailWarningOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeProfileEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback resendWelcomeEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AzuPass() {
            this.Url = global::AzuPassProfileMgr.Properties.Settings.Default.AzuPassProfileMgr_TEICOCF_WebServices_AzuPass;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event _LogOnCompletedEventHandler _LogOnCompleted;
        
        /// <remarks/>
        public event _LogOnPlusCompletedEventHandler _LogOnPlusCompleted;
        
        /// <remarks/>
        public event _getProfileFavoritesCompletedEventHandler _getProfileFavoritesCompleted;
        
        /// <remarks/>
        public event _getServicedApplicationsCompletedEventHandler _getServicedApplicationsCompleted;
        
        /// <remarks/>
        public event _getServiceAdminsCompletedEventHandler _getServiceAdminsCompleted;
        
        /// <remarks/>
        public event _getProfileManagerURLCompletedEventHandler _getProfileManagerURLCompleted;
        
        /// <remarks/>
        public event _getAboutCompletedEventHandler _getAboutCompleted;
        
        /// <remarks/>
        public event _getLogoImageSrcCompletedEventHandler _getLogoImageSrcCompleted;
        
        /// <remarks/>
        public event _getServiceShortNameCompletedEventHandler _getServiceShortNameCompleted;
        
        /// <remarks/>
        public event _getServiceFullNameCompletedEventHandler _getServiceFullNameCompleted;
        
        /// <remarks/>
        public event _getListCatOcupacionalesCompletedEventHandler _getListCatOcupacionalesCompleted;
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        public event EditProfileCompletedEventHandler EditProfileCompleted;
        
        /// <remarks/>
        public event PrepareNewProfileCompletedEventHandler PrepareNewProfileCompleted;
        
        /// <remarks/>
        public event UpdateProfileCompletedEventHandler UpdateProfileCompleted;
        
        /// <remarks/>
        public event getPasswdRequerimentsCompletedEventHandler getPasswdRequerimentsCompleted;
        
        /// <remarks/>
        public event getChangeProfilePasswdWarningCompletedEventHandler getChangeProfilePasswdWarningCompleted;
        
        /// <remarks/>
        public event changeProfilePasswdCompletedEventHandler changeProfilePasswdCompleted;
        
        /// <remarks/>
        public event getChangeProfileEmailWarningCompletedEventHandler getChangeProfileEmailWarningCompleted;
        
        /// <remarks/>
        public event changeProfileEmailCompletedEventHandler changeProfileEmailCompleted;
        
        /// <remarks/>
        public event resendWelcomeEmailCompletedEventHandler resendWelcomeEmailCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_LogOn", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool _LogOn(string e_mail, string Passwd, string clientAppName, string clientAppURL, enuApplicationState appState) {
            object[] results = this.Invoke("_LogOn", new object[] {
                        e_mail,
                        Passwd,
                        clientAppName,
                        clientAppURL,
                        appState});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void _LogOnAsync(string e_mail, string Passwd, string clientAppName, string clientAppURL, enuApplicationState appState) {
            this._LogOnAsync(e_mail, Passwd, clientAppName, clientAppURL, appState, null);
        }
        
        /// <remarks/>
        public void _LogOnAsync(string e_mail, string Passwd, string clientAppName, string clientAppURL, enuApplicationState appState, object userState) {
            if ((this._LogOnOperationCompleted == null)) {
                this._LogOnOperationCompleted = new System.Threading.SendOrPostCallback(this.On_LogOnOperationCompleted);
            }
            this.InvokeAsync("_LogOn", new object[] {
                        e_mail,
                        Passwd,
                        clientAppName,
                        clientAppURL,
                        appState}, this._LogOnOperationCompleted, userState);
        }
        
        private void On_LogOnOperationCompleted(object arg) {
            if ((this._LogOnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._LogOnCompleted(this, new _LogOnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_LogOnPlus", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _LogOnPlus(string e_mail, string Passwd, string clientAppName, string clientAppURL, enuApplicationState appState) {
            object[] results = this.Invoke("_LogOnPlus", new object[] {
                        e_mail,
                        Passwd,
                        clientAppName,
                        clientAppURL,
                        appState});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _LogOnPlusAsync(string e_mail, string Passwd, string clientAppName, string clientAppURL, enuApplicationState appState) {
            this._LogOnPlusAsync(e_mail, Passwd, clientAppName, clientAppURL, appState, null);
        }
        
        /// <remarks/>
        public void _LogOnPlusAsync(string e_mail, string Passwd, string clientAppName, string clientAppURL, enuApplicationState appState, object userState) {
            if ((this._LogOnPlusOperationCompleted == null)) {
                this._LogOnPlusOperationCompleted = new System.Threading.SendOrPostCallback(this.On_LogOnPlusOperationCompleted);
            }
            this.InvokeAsync("_LogOnPlus", new object[] {
                        e_mail,
                        Passwd,
                        clientAppName,
                        clientAppURL,
                        appState}, this._LogOnPlusOperationCompleted, userState);
        }
        
        private void On_LogOnPlusOperationCompleted(object arg) {
            if ((this._LogOnPlusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._LogOnPlusCompleted(this, new _LogOnPlusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_getProfileFavorites", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _getProfileFavorites(string e_mail, string Passwd, int cantEnLista) {
            object[] results = this.Invoke("_getProfileFavorites", new object[] {
                        e_mail,
                        Passwd,
                        cantEnLista});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _getProfileFavoritesAsync(string e_mail, string Passwd, int cantEnLista) {
            this._getProfileFavoritesAsync(e_mail, Passwd, cantEnLista, null);
        }
        
        /// <remarks/>
        public void _getProfileFavoritesAsync(string e_mail, string Passwd, int cantEnLista, object userState) {
            if ((this._getProfileFavoritesOperationCompleted == null)) {
                this._getProfileFavoritesOperationCompleted = new System.Threading.SendOrPostCallback(this.On_getProfileFavoritesOperationCompleted);
            }
            this.InvokeAsync("_getProfileFavorites", new object[] {
                        e_mail,
                        Passwd,
                        cantEnLista}, this._getProfileFavoritesOperationCompleted, userState);
        }
        
        private void On_getProfileFavoritesOperationCompleted(object arg) {
            if ((this._getProfileFavoritesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._getProfileFavoritesCompleted(this, new _getProfileFavoritesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_getServicedApplications", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _getServicedApplications(int listTop) {
            object[] results = this.Invoke("_getServicedApplications", new object[] {
                        listTop});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _getServicedApplicationsAsync(int listTop) {
            this._getServicedApplicationsAsync(listTop, null);
        }
        
        /// <remarks/>
        public void _getServicedApplicationsAsync(int listTop, object userState) {
            if ((this._getServicedApplicationsOperationCompleted == null)) {
                this._getServicedApplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_getServicedApplicationsOperationCompleted);
            }
            this.InvokeAsync("_getServicedApplications", new object[] {
                        listTop}, this._getServicedApplicationsOperationCompleted, userState);
        }
        
        private void On_getServicedApplicationsOperationCompleted(object arg) {
            if ((this._getServicedApplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._getServicedApplicationsCompleted(this, new _getServicedApplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_getServiceAdmins", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _getServiceAdmins() {
            object[] results = this.Invoke("_getServiceAdmins", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _getServiceAdminsAsync() {
            this._getServiceAdminsAsync(null);
        }
        
        /// <remarks/>
        public void _getServiceAdminsAsync(object userState) {
            if ((this._getServiceAdminsOperationCompleted == null)) {
                this._getServiceAdminsOperationCompleted = new System.Threading.SendOrPostCallback(this.On_getServiceAdminsOperationCompleted);
            }
            this.InvokeAsync("_getServiceAdmins", new object[0], this._getServiceAdminsOperationCompleted, userState);
        }
        
        private void On_getServiceAdminsOperationCompleted(object arg) {
            if ((this._getServiceAdminsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._getServiceAdminsCompleted(this, new _getServiceAdminsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_getProfileManagerURL", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string _getProfileManagerURL() {
            object[] results = this.Invoke("_getProfileManagerURL", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void _getProfileManagerURLAsync() {
            this._getProfileManagerURLAsync(null);
        }
        
        /// <remarks/>
        public void _getProfileManagerURLAsync(object userState) {
            if ((this._getProfileManagerURLOperationCompleted == null)) {
                this._getProfileManagerURLOperationCompleted = new System.Threading.SendOrPostCallback(this.On_getProfileManagerURLOperationCompleted);
            }
            this.InvokeAsync("_getProfileManagerURL", new object[0], this._getProfileManagerURLOperationCompleted, userState);
        }
        
        private void On_getProfileManagerURLOperationCompleted(object arg) {
            if ((this._getProfileManagerURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._getProfileManagerURLCompleted(this, new _getProfileManagerURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_getAbout", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string _getAbout() {
            object[] results = this.Invoke("_getAbout", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void _getAboutAsync() {
            this._getAboutAsync(null);
        }
        
        /// <remarks/>
        public void _getAboutAsync(object userState) {
            if ((this._getAboutOperationCompleted == null)) {
                this._getAboutOperationCompleted = new System.Threading.SendOrPostCallback(this.On_getAboutOperationCompleted);
            }
            this.InvokeAsync("_getAbout", new object[0], this._getAboutOperationCompleted, userState);
        }
        
        private void On_getAboutOperationCompleted(object arg) {
            if ((this._getAboutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._getAboutCompleted(this, new _getAboutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_getLogoImageSrc", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string _getLogoImageSrc() {
            object[] results = this.Invoke("_getLogoImageSrc", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void _getLogoImageSrcAsync() {
            this._getLogoImageSrcAsync(null);
        }
        
        /// <remarks/>
        public void _getLogoImageSrcAsync(object userState) {
            if ((this._getLogoImageSrcOperationCompleted == null)) {
                this._getLogoImageSrcOperationCompleted = new System.Threading.SendOrPostCallback(this.On_getLogoImageSrcOperationCompleted);
            }
            this.InvokeAsync("_getLogoImageSrc", new object[0], this._getLogoImageSrcOperationCompleted, userState);
        }
        
        private void On_getLogoImageSrcOperationCompleted(object arg) {
            if ((this._getLogoImageSrcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._getLogoImageSrcCompleted(this, new _getLogoImageSrcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_getServiceShortName", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string _getServiceShortName() {
            object[] results = this.Invoke("_getServiceShortName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void _getServiceShortNameAsync() {
            this._getServiceShortNameAsync(null);
        }
        
        /// <remarks/>
        public void _getServiceShortNameAsync(object userState) {
            if ((this._getServiceShortNameOperationCompleted == null)) {
                this._getServiceShortNameOperationCompleted = new System.Threading.SendOrPostCallback(this.On_getServiceShortNameOperationCompleted);
            }
            this.InvokeAsync("_getServiceShortName", new object[0], this._getServiceShortNameOperationCompleted, userState);
        }
        
        private void On_getServiceShortNameOperationCompleted(object arg) {
            if ((this._getServiceShortNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._getServiceShortNameCompleted(this, new _getServiceShortNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_getServiceFullName", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string _getServiceFullName() {
            object[] results = this.Invoke("_getServiceFullName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void _getServiceFullNameAsync() {
            this._getServiceFullNameAsync(null);
        }
        
        /// <remarks/>
        public void _getServiceFullNameAsync(object userState) {
            if ((this._getServiceFullNameOperationCompleted == null)) {
                this._getServiceFullNameOperationCompleted = new System.Threading.SendOrPostCallback(this.On_getServiceFullNameOperationCompleted);
            }
            this.InvokeAsync("_getServiceFullName", new object[0], this._getServiceFullNameOperationCompleted, userState);
        }
        
        private void On_getServiceFullNameOperationCompleted(object arg) {
            if ((this._getServiceFullNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._getServiceFullNameCompleted(this, new _getServiceFullNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/_getListCatOcupacionales", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet _getListCatOcupacionales() {
            object[] results = this.Invoke("_getListCatOcupacionales", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void _getListCatOcupacionalesAsync() {
            this._getListCatOcupacionalesAsync(null);
        }
        
        /// <remarks/>
        public void _getListCatOcupacionalesAsync(object userState) {
            if ((this._getListCatOcupacionalesOperationCompleted == null)) {
                this._getListCatOcupacionalesOperationCompleted = new System.Threading.SendOrPostCallback(this.On_getListCatOcupacionalesOperationCompleted);
            }
            this.InvokeAsync("_getListCatOcupacionales", new object[0], this._getListCatOcupacionalesOperationCompleted, userState);
        }
        
        private void On_getListCatOcupacionalesOperationCompleted(object arg) {
            if ((this._getListCatOcupacionalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._getListCatOcupacionalesCompleted(this, new _getListCatOcupacionalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/Register", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Register(string Nombre, string Apellidos, string e_mail, System.DateTime FechaNac, enuSexo Sexo, int IdCatOcupacional, string DescripcionIntereses) {
            object[] results = this.Invoke("Register", new object[] {
                        Nombre,
                        Apellidos,
                        e_mail,
                        FechaNac,
                        Sexo,
                        IdCatOcupacional,
                        DescripcionIntereses});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAsync(string Nombre, string Apellidos, string e_mail, System.DateTime FechaNac, enuSexo Sexo, int IdCatOcupacional, string DescripcionIntereses) {
            this.RegisterAsync(Nombre, Apellidos, e_mail, FechaNac, Sexo, IdCatOcupacional, DescripcionIntereses, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(string Nombre, string Apellidos, string e_mail, System.DateTime FechaNac, enuSexo Sexo, int IdCatOcupacional, string DescripcionIntereses, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        Nombre,
                        Apellidos,
                        e_mail,
                        FechaNac,
                        Sexo,
                        IdCatOcupacional,
                        DescripcionIntereses}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/EditProfile", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EditProfile(string Email, string Passwd) {
            object[] results = this.Invoke("EditProfile", new object[] {
                        Email,
                        Passwd});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EditProfileAsync(string Email, string Passwd) {
            this.EditProfileAsync(Email, Passwd, null);
        }
        
        /// <remarks/>
        public void EditProfileAsync(string Email, string Passwd, object userState) {
            if ((this.EditProfileOperationCompleted == null)) {
                this.EditProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditProfileOperationCompleted);
            }
            this.InvokeAsync("EditProfile", new object[] {
                        Email,
                        Passwd}, this.EditProfileOperationCompleted, userState);
        }
        
        private void OnEditProfileOperationCompleted(object arg) {
            if ((this.EditProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditProfileCompleted(this, new EditProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/PrepareNewProfile", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet PrepareNewProfile() {
            object[] results = this.Invoke("PrepareNewProfile", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void PrepareNewProfileAsync() {
            this.PrepareNewProfileAsync(null);
        }
        
        /// <remarks/>
        public void PrepareNewProfileAsync(object userState) {
            if ((this.PrepareNewProfileOperationCompleted == null)) {
                this.PrepareNewProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrepareNewProfileOperationCompleted);
            }
            this.InvokeAsync("PrepareNewProfile", new object[0], this.PrepareNewProfileOperationCompleted, userState);
        }
        
        private void OnPrepareNewProfileOperationCompleted(object arg) {
            if ((this.PrepareNewProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrepareNewProfileCompleted(this, new PrepareNewProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/UpdateProfile", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateProfile(string e_mail, string Passwd, string Nombre, string Apellidos, System.DateTime FechaNac, enuSexo Sexo, int IdCatOcupacional, string DescripcionIntereses) {
            object[] results = this.Invoke("UpdateProfile", new object[] {
                        e_mail,
                        Passwd,
                        Nombre,
                        Apellidos,
                        FechaNac,
                        Sexo,
                        IdCatOcupacional,
                        DescripcionIntereses});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(string e_mail, string Passwd, string Nombre, string Apellidos, System.DateTime FechaNac, enuSexo Sexo, int IdCatOcupacional, string DescripcionIntereses) {
            this.UpdateProfileAsync(e_mail, Passwd, Nombre, Apellidos, FechaNac, Sexo, IdCatOcupacional, DescripcionIntereses, null);
        }
        
        /// <remarks/>
        public void UpdateProfileAsync(string e_mail, string Passwd, string Nombre, string Apellidos, System.DateTime FechaNac, enuSexo Sexo, int IdCatOcupacional, string DescripcionIntereses, object userState) {
            if ((this.UpdateProfileOperationCompleted == null)) {
                this.UpdateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProfileOperationCompleted);
            }
            this.InvokeAsync("UpdateProfile", new object[] {
                        e_mail,
                        Passwd,
                        Nombre,
                        Apellidos,
                        FechaNac,
                        Sexo,
                        IdCatOcupacional,
                        DescripcionIntereses}, this.UpdateProfileOperationCompleted, userState);
        }
        
        private void OnUpdateProfileOperationCompleted(object arg) {
            if ((this.UpdateProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProfileCompleted(this, new UpdateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/getPasswdRequeriments", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public passwordRequeriments getPasswdRequeriments() {
            object[] results = this.Invoke("getPasswdRequeriments", new object[0]);
            return ((passwordRequeriments)(results[0]));
        }
        
        /// <remarks/>
        public void getPasswdRequerimentsAsync() {
            this.getPasswdRequerimentsAsync(null);
        }
        
        /// <remarks/>
        public void getPasswdRequerimentsAsync(object userState) {
            if ((this.getPasswdRequerimentsOperationCompleted == null)) {
                this.getPasswdRequerimentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPasswdRequerimentsOperationCompleted);
            }
            this.InvokeAsync("getPasswdRequeriments", new object[0], this.getPasswdRequerimentsOperationCompleted, userState);
        }
        
        private void OngetPasswdRequerimentsOperationCompleted(object arg) {
            if ((this.getPasswdRequerimentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPasswdRequerimentsCompleted(this, new getPasswdRequerimentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/getChangeProfilePasswdWarning", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getChangeProfilePasswdWarning() {
            object[] results = this.Invoke("getChangeProfilePasswdWarning", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getChangeProfilePasswdWarningAsync() {
            this.getChangeProfilePasswdWarningAsync(null);
        }
        
        /// <remarks/>
        public void getChangeProfilePasswdWarningAsync(object userState) {
            if ((this.getChangeProfilePasswdWarningOperationCompleted == null)) {
                this.getChangeProfilePasswdWarningOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChangeProfilePasswdWarningOperationCompleted);
            }
            this.InvokeAsync("getChangeProfilePasswdWarning", new object[0], this.getChangeProfilePasswdWarningOperationCompleted, userState);
        }
        
        private void OngetChangeProfilePasswdWarningOperationCompleted(object arg) {
            if ((this.getChangeProfilePasswdWarningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChangeProfilePasswdWarningCompleted(this, new getChangeProfilePasswdWarningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/changeProfilePasswd", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool changeProfilePasswd(string e_mail, string current_Passwd, string new_Passwd) {
            object[] results = this.Invoke("changeProfilePasswd", new object[] {
                        e_mail,
                        current_Passwd,
                        new_Passwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void changeProfilePasswdAsync(string e_mail, string current_Passwd, string new_Passwd) {
            this.changeProfilePasswdAsync(e_mail, current_Passwd, new_Passwd, null);
        }
        
        /// <remarks/>
        public void changeProfilePasswdAsync(string e_mail, string current_Passwd, string new_Passwd, object userState) {
            if ((this.changeProfilePasswdOperationCompleted == null)) {
                this.changeProfilePasswdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeProfilePasswdOperationCompleted);
            }
            this.InvokeAsync("changeProfilePasswd", new object[] {
                        e_mail,
                        current_Passwd,
                        new_Passwd}, this.changeProfilePasswdOperationCompleted, userState);
        }
        
        private void OnchangeProfilePasswdOperationCompleted(object arg) {
            if ((this.changeProfilePasswdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeProfilePasswdCompleted(this, new changeProfilePasswdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/getChangeProfileEmailWarning", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getChangeProfileEmailWarning() {
            object[] results = this.Invoke("getChangeProfileEmailWarning", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getChangeProfileEmailWarningAsync() {
            this.getChangeProfileEmailWarningAsync(null);
        }
        
        /// <remarks/>
        public void getChangeProfileEmailWarningAsync(object userState) {
            if ((this.getChangeProfileEmailWarningOperationCompleted == null)) {
                this.getChangeProfileEmailWarningOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChangeProfileEmailWarningOperationCompleted);
            }
            this.InvokeAsync("getChangeProfileEmailWarning", new object[0], this.getChangeProfileEmailWarningOperationCompleted, userState);
        }
        
        private void OngetChangeProfileEmailWarningOperationCompleted(object arg) {
            if ((this.getChangeProfileEmailWarningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChangeProfileEmailWarningCompleted(this, new getChangeProfileEmailWarningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/changeProfileEmail", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string changeProfileEmail(string current_e_mail, string Passwd, string new_e_mail) {
            object[] results = this.Invoke("changeProfileEmail", new object[] {
                        current_e_mail,
                        Passwd,
                        new_e_mail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void changeProfileEmailAsync(string current_e_mail, string Passwd, string new_e_mail) {
            this.changeProfileEmailAsync(current_e_mail, Passwd, new_e_mail, null);
        }
        
        /// <remarks/>
        public void changeProfileEmailAsync(string current_e_mail, string Passwd, string new_e_mail, object userState) {
            if ((this.changeProfileEmailOperationCompleted == null)) {
                this.changeProfileEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeProfileEmailOperationCompleted);
            }
            this.InvokeAsync("changeProfileEmail", new object[] {
                        current_e_mail,
                        Passwd,
                        new_e_mail}, this.changeProfileEmailOperationCompleted, userState);
        }
        
        private void OnchangeProfileEmailOperationCompleted(object arg) {
            if ((this.changeProfileEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeProfileEmailCompleted(this, new changeProfileEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/resendWelcomeEmail", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool resendWelcomeEmail(string e_mail) {
            object[] results = this.Invoke("resendWelcomeEmail", new object[] {
                        e_mail});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void resendWelcomeEmailAsync(string e_mail) {
            this.resendWelcomeEmailAsync(e_mail, null);
        }
        
        /// <remarks/>
        public void resendWelcomeEmailAsync(string e_mail, object userState) {
            if ((this.resendWelcomeEmailOperationCompleted == null)) {
                this.resendWelcomeEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresendWelcomeEmailOperationCompleted);
            }
            this.InvokeAsync("resendWelcomeEmail", new object[] {
                        e_mail}, this.resendWelcomeEmailOperationCompleted, userState);
        }
        
        private void OnresendWelcomeEmailOperationCompleted(object arg) {
            if ((this.resendWelcomeEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resendWelcomeEmailCompleted(this, new resendWelcomeEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.cf.minaz.cu/Test", RequestNamespace="http://webservices.cf.minaz.cu/", ResponseNamespace="http://webservices.cf.minaz.cu/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        /// <remarks/>
        public void TestAsync(object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[0], this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.cf.minaz.cu/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://webservices.cf.minaz.cu/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string appClienteField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        public string AppCliente {
            get {
                return this.appClienteField;
            }
            set {
                this.appClienteField = value;
            }
        }
        
        /// <comentarios/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.cf.minaz.cu/")]
    public partial class passwordRequeriments {
        
        private byte pwdMinCharsField;
        
        private byte pwdMaxCharsField;
        
        private bool pwdMustDiferUserNameField;
        
        /// <comentarios/>
        public byte pwdMinChars {
            get {
                return this.pwdMinCharsField;
            }
            set {
                this.pwdMinCharsField = value;
            }
        }
        
        /// <comentarios/>
        public byte pwdMaxChars {
            get {
                return this.pwdMaxCharsField;
            }
            set {
                this.pwdMaxCharsField = value;
            }
        }
        
        /// <comentarios/>
        public bool pwdMustDiferUserName {
            get {
                return this.pwdMustDiferUserNameField;
            }
            set {
                this.pwdMustDiferUserNameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.cf.minaz.cu/")]
    public enum enuApplicationState {
        
        /// <comentarios/>
        Debug,
        
        /// <comentarios/>
        Release,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.cf.minaz.cu/")]
    public enum enuSexo {
        
        /// <comentarios/>
        F,
        
        /// <comentarios/>
        M,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _LogOnCompletedEventHandler(object sender, _LogOnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _LogOnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _LogOnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _LogOnPlusCompletedEventHandler(object sender, _LogOnPlusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _LogOnPlusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _LogOnPlusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _getProfileFavoritesCompletedEventHandler(object sender, _getProfileFavoritesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _getProfileFavoritesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _getProfileFavoritesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _getServicedApplicationsCompletedEventHandler(object sender, _getServicedApplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _getServicedApplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _getServicedApplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _getServiceAdminsCompletedEventHandler(object sender, _getServiceAdminsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _getServiceAdminsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _getServiceAdminsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _getProfileManagerURLCompletedEventHandler(object sender, _getProfileManagerURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _getProfileManagerURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _getProfileManagerURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _getAboutCompletedEventHandler(object sender, _getAboutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _getAboutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _getAboutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _getLogoImageSrcCompletedEventHandler(object sender, _getLogoImageSrcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _getLogoImageSrcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _getLogoImageSrcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _getServiceShortNameCompletedEventHandler(object sender, _getServiceShortNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _getServiceShortNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _getServiceShortNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _getServiceFullNameCompletedEventHandler(object sender, _getServiceFullNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _getServiceFullNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _getServiceFullNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void _getListCatOcupacionalesCompletedEventHandler(object sender, _getListCatOcupacionalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _getListCatOcupacionalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _getListCatOcupacionalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RegisterCompletedEventHandler(object sender, RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void EditProfileCompletedEventHandler(object sender, EditProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PrepareNewProfileCompletedEventHandler(object sender, PrepareNewProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrepareNewProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrepareNewProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateProfileCompletedEventHandler(object sender, UpdateProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getPasswdRequerimentsCompletedEventHandler(object sender, getPasswdRequerimentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPasswdRequerimentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPasswdRequerimentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public passwordRequeriments Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((passwordRequeriments)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getChangeProfilePasswdWarningCompletedEventHandler(object sender, getChangeProfilePasswdWarningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChangeProfilePasswdWarningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChangeProfilePasswdWarningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void changeProfilePasswdCompletedEventHandler(object sender, changeProfilePasswdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeProfilePasswdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeProfilePasswdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getChangeProfileEmailWarningCompletedEventHandler(object sender, getChangeProfileEmailWarningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChangeProfileEmailWarningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChangeProfileEmailWarningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void changeProfileEmailCompletedEventHandler(object sender, changeProfileEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeProfileEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeProfileEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void resendWelcomeEmailCompletedEventHandler(object sender, resendWelcomeEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resendWelcomeEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal resendWelcomeEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591